### ISSUE TITLE
Add sstyling to the Todo react application

### ISSUE THREAD

**Issue by ajay-rawat-9** [ajay-rawat-9/react-application#1]
The react-application repository has a folder react application which contains a todo application. The application is currently missing the styling. The required files are already created which are: App.css and index.css. 
The repo link is [React-application](https://github.com/ajay-rawat-9/react-application/tree/react-application/react-application).
The changes should be committed in the react-application branch [NOTE: Not the master branch].

**Comment by siwamsingh** [comment]
Hii @ajay-rawat-9 
I would like to work on this issue . 😊
I am quite decent in styling . 💯

Kindly assign this issue to me I would like to contribute to this project.

**Comment by ajay-rawat-9** [comment]
> Hii @ajay-rawat-9 I would like to work on this issue . 😊 I am quite decent in styling . 💯
> 
> Kindly assign this issue to me I would like to contribute to this project.

Hi @siwamsingh 
Sure, I have assigned this issue to you. Thanks!

**Comment by siwamsingh** [comment]
Thanks for assigning the issue to me 
i have made a few adjustments.
i hope you like it.
<img width="710" alt="Screenshot 2023-12-11 011438" src="https://github.com/ajay-rawat-9/react-application/assets/140843501/5736c6b2-636e-4881-bb4d-99226929ce18">

**Comment by ajay-rawat-9** [comment]
It's good, you can go ahead with it. 
Thanks, Siwam!

**Comment by ajay-rawat-9** [comment]
Hi @siwamsingh, can you push it to the react-application branch instead?

**Comment by siwamsingh** [comment]
Ok will do that

**Comment by siwamsingh** [comment]
Well the issue didn't close on its own 🤔
So does this is issue still counts as unsolved?

**Comment by ajay-rawat-9** [comment]
Thanks @siwamsingh for contributing the changes.

**Comment by siwamsingh** [comment]
Thank for this opportunity 🙏
